/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.svg",
        "heroText": "大米饭的Blog",
        "tagline": "记录我的笔记~",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-1d79e333",
      "path": "/"
    },
    {
      "title": "React 生命周期图（旧）V16.4 前",
      "frontmatter": {
        "sidebar": "auto"
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-39c31ca8",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "constructor",
          "slug": "constructor"
        },
        {
          "level": 2,
          "title": "⭕ ~~componentWillMount~~",
          "slug": "⭕-componentwillmount"
        },
        {
          "level": 2,
          "title": "render",
          "slug": "render"
        },
        {
          "level": 2,
          "title": "componentDidMount",
          "slug": "componentdidmount"
        },
        {
          "level": 2,
          "title": "⭕ ~~componentWillReceiveProps~~",
          "slug": "⭕-componentwillreceiveprops"
        },
        {
          "level": 2,
          "title": "👀 shouldComponentUpdate",
          "slug": "👀-shouldcomponentupdate"
        },
        {
          "level": 2,
          "title": "⭕ ~~componentWillUpdate~~",
          "slug": "⭕-componentwillupdate"
        },
        {
          "level": 2,
          "title": "componentDidUpdate",
          "slug": "componentdidupdate"
        },
        {
          "level": 2,
          "title": "componentWillUnmount",
          "slug": "componentwillunmount"
        },
        {
          "level": 2,
          "title": "static getDerivedStateFromProps",
          "slug": "static-getderivedstatefromprops"
        },
        {
          "level": 2,
          "title": "getSnapshotBeforeUpdata",
          "slug": "getsnapshotbeforeupdata"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/logo.svg",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "About",
        "link": "/about"
      },
      {
        "text": "More",
        "items": [
          {
            "text": "Ground1",
            "link": "/gound"
          }
        ]
      }
    ]
  }
}